### ISSUE TITLE
Travis CI didn't run automated test

### ISSUE THREAD

**Issue by endiliey** [Kindev/fundraisee-api#7]
## Motivation
Based on our travis CI yaml, we only run test coverage but not the test itself

Related
https://github.com/Kindev/fundraisee-api/blob/ca93370ec08f1e3c6fc49043ed8f311327a48d12/.travis.yml#L7-L8

We should add the part of running the test 😄 
```yaml
python manage.py test
```

**Comment by endiliey** [comment]
Yup 😁

**Comment by michjk** [comment]
I am not sure whether I am right, but I think travis ci run the test script
![image](https://user-images.githubusercontent.com/11803421/41655919-fdfe0340-74c0-11e8-8032-1cfb652882c6.png)

**Comment by endiliey** [comment]
Good analysis. As stated in the issue, it is indeed being run, it's just that it's being run with coverage.py as a wrapper.

I saw some tutorial online using both scripts and some only using current script. So it made me wonder if we should run it separately.

But i think we can close this
